language: node_js
node_js:
    - "0.12"
install:
    - npm install
after_script:
    - NODE_ENV=test
    - istanbul cover ./node_modules/mocha/bin/_mocha app/tests/test.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - rm -rf ./coverage
deploy:
    provider: heroku
    api_key:
        secure: c0c56c84-5ad9-48d2-9cfb-3d7d738cfff9
    app: funpaste
    on:
        repo: nigh7ynigh7/funpaste
